### ISSUE TITLE
Greenclip Support

### ISSUE THREAD

**Issue by arkhan** [redguardtoo/cliphist#13] opened 2017-12-29 17:19 UTC
Hello, it's possible to add support for greenclipt
https://github.com/erebe/greenclip
thanks

**Comment by redguardtoo** [comment] 2018-02-10 02:44
yeah, that's doable, I need do some research on its code

**Comment by arkhan** [comment] 2018-11-20 13:27
Greetings, I'm trying to integrate greenclip and [cliphist](https://github.com/mrichar1/clipster), but I still do not know how to do it
``` emacs-lisp
(list (s-split "\t" (shell-command-to-string "clipster -c -o -n 5 | awk '{gsub(/^ +| +$/,\"\")} {print \"\" $0 \"\"}'")))
```
I think that line can be used to obtain the elements of the clipboard

**Comment by redguardtoo** [comment] 2018-11-21 02:37
Pull request is welcomed.

I'm not sure how to use greepclip.

Looks you need run `greeclip daemon` as clipboard server first. paste something, then run `greenclip print` to list all items. I noticed `line-feed` is changed into "\n" (one slash, one "n" character).

Check below code:
```lisp
(autoload 'cliphist-flycut-read-items "cliphist-flycut" nil)
(autoload 'cliphist-parcellite-read-items "cliphist-parcellite" nil)
(autoload 'cliphist-clipit-read-items "cliphist-clipit" nil)
```

For example, you could use `cliphist-clipit-read-items` as sample,
`(split-string (shell-command-to-string "greenclip history") "[\r\n]+")` could be a good start.
```

**Comment by folliehiyuki** [comment] 2021-02-20 02:30
Hi. I use `greenclip` but am really new to Emacs (my elisp-fu nearly doesn't exist), so the best I can do right now is to provide some information.
As stated with examples in `greenclip`'s readme, an ideal way to retrieve an item from clipboard is with the command:
```
greenclip print | sed '/^$/d' | ???????????? | xargs -r -d'\n' -I '{}' greenclip print '{}'
```
where ????????? is our entry-selection program of choice. It would be nice if we can somehow "pipe" that into `ivy` :) The last `greenclip print` just re-copy the selected text and put it on top list again.

**Comment by folliehiyuki** [comment] 2021-02-22 07:20
I made this with my little knowledge. It kinda works on its own. The problem is that when `item` is big, and contain vague characters like `$`, some shells (like `fish-shell`) will not like it and error out.
```emacs-lisp
(defun ivy-greenclip ()
  "Select an item from clipboard history and re-copy it"
  (interactive)
  (let* ((history (split-string (shell-command-to-string "greenclip print | sed '/^$/d'") "[\r\n]+")))
    (ivy-read "Copy item from entry: "
              history
              :action (lambda (item)
                        (shell-command (concat "greenclip print '" item "'"))))))
```

`greenclip` replaces \n and \r with \xA0 before saving the item to the history file, so if we can do some regex replacing with `item`, that last command will not be needed.

**Comment by redguardtoo** [comment] 2021-02-22 13:06
You can send me a pull request if you want my code merged.

@FollieHiyuki , try `call-process` api. `shell-command` is used when I was still not good at Emacs Lisp.

I don't think you need `sed`. Emacs has its own API `replace-regexp-in-string`.

**Comment by folliehiyuki** [comment] 2021-02-22 17:40
Thanks. I have some more questions:
- How can I regexp-replace the character `\xa0` in Emacs. I'm struggling with it :)
- And can you provide some guideline on how to integrate this into `cliphist`, since til now what I have done only touched x clipboard, and haven't done anything with Emacs kill ring at all.

**Comment by redguardtoo** [comment] 2021-02-23 00:42
https://www.gnu.org/software/emacs/manual/html_node/elisp/Non_002dASCII-in-Strings.html#Non_002dASCII-in-Strings

https://github.com/redguardtoo/cliphist/blob/master/cliphist.el#L131

**Comment by folliehiyuki** [comment] 2021-02-23 02:36
Thanks for the info. I will take a look.
This might take a while, since I have to learn lisp along the way as well.

**Comment by redguardtoo** [comment] 2021-03-01 07:49
1ef5045 support greenclip (Chen Bin)

**Comment by folliehiyuki** [comment] 2021-03-01 13:13
Thanks for your work, meanwhile I'm still fighting brackets :)
I tried it out and it works.
1 concern though: I tend to not have my clipboard clutter up, so I usually delete the clipboard history once in while. `cliphist` currently saves cache when reading items. Adding a variable so that the users can control the caching behavior would be nice.

**Comment by redguardtoo** [comment] 2021-03-02 05:47
cliphist will synchronise  cache with clipboard manager if it's not empty. So you don't need worry about clearing cache.

If you really need manually empty cache, eval `(setq cliphist-items nil)`.

**Comment by folliehiyuki** [comment] 2021-03-02 08:16
That was the last missing piece I needed.
I think you can close the issue.

**Closed as completed** 2021-03-02 09:17 UTC
